BuildingDepot/app/central/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SelectMultipleField, SubmitField, SelectField, BooleanField
from wtforms.validators import DataRequired


class TagTypeForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    parents = SelectMultipleField('Parents')
    submit = SubmitField('Submit')


class BuildingTemplateForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    tag_types = SelectMultipleField('Tag types')
    submit = SubmitField('Submit')


class BuildingForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    template = SelectField('Template', validators=[DataRequired()])
    submit = SubmitField('Submit')


class RoleForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    permission = SelectField('Permission', choices=[('r', 'r'), ('r/w', 'r/w')], validators=[DataRequired()])
    type = SelectField('Type',
                       choices=[('default', 'default'), ('local', 'local'), ('super', 'super')],
                       validators=[DataRequired()])
    submit = SubmitField('Submit')


class DataServiceForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    host = StringField('Host', validators=[DataRequired()])
    port = StringField('Port', validators=[DataRequired()])
    submit = SubmitField('Submit')

BuildingDepot/app/central/__init__.py
from flask import Blueprint

central = Blueprint('central', __name__)

from . import views

BuildingDepot/app/central/views.py
from flask import render_template, request, redirect, url_for, jsonify
from . import central
from ..models.cs_models import *
from flask.ext.login import login_required
from app.common import PAGE_SIZE
from .forms import *
from .utils import get_choices, get_tag_descendant_pairs
from werkzeug.security import generate_password_hash


@central.route('/tagtype', methods=['GET', 'POST'])
@login_required
def tagtype():
    page = request.args.get('page', 1, type=int)
    skip_size = (page-1)*PAGE_SIZE
    objs = TagType.objects().skip(skip_size).limit(PAGE_SIZE)
    for obj in objs:
        if not obj.children and BuildingTemplate._get_collection().find({'tag_types': obj.name}).count() == 0:
            obj.can_delete = True
        else:
            obj.can_delete = False
    form = TagTypeForm()
    form.parents.choices = get_choices(TagType)
    if form.validate_on_submit():
        TagType(name=str(form.name.data),
                description=str(form.description.data),
                parents=form.parents.data).save()
        for parent in form.parents.data:
            collection = TagType._get_collection()
            collection.update(
                {'name': parent},
                {'$addToSet': {'children': str(form.name.data)}}
            )
        return redirect(url_for('central.tagtype'))
    return render_template('central/tagtype.html', objs=objs, form=form)


@central.route('/tagtype_delete', methods=['POST'])
@login_required
def tagtype_delete():
    name = request.form.get('name')
    TagType.objects(name=name).delete()
    collection = TagType._get_collection()
    collection.update(
        {'children': name},
        {'$pull': {'children': name}},
        multi=True
    )
    return redirect(url_for('central.tagtype'))


@central.route('/role', methods=['GET', 'POST'])
@login_required
def role():
    objs = Role.objects
    for obj in objs:
        if User.objects(role=obj).count() > 0:
            obj.can_delete = False
        else:
            obj.can_delete = True
    form = RoleForm()
    if form.validate_on_submit():
        Role(name=str(form.name.data),
             description=str(form.description.data),
             permission=form.permission.data,
             type=form.type.data).save()
        return redirect(url_for('central.role'))
    return render_template('central/role.html', objs=objs, form=form)


@central.route('/role_delete', methods=['POST'])
@login_required
def role_delete():
    name = request.form.get('name')
    Role.objects(name=name).delete()
    return redirect(url_for('central.role'))


@central.route('/buildingtemplate', methods=['GET', 'POST'])
@login_required
def buildingtemplate():
    page = request.args.get('page', 1, type=int)
    skip_size = (page-1)*PAGE_SIZE
    objs = BuildingTemplate.objects().skip(skip_size).limit(PAGE_SIZE)
    for obj in objs:
        if Building.objects(template=obj.name).count() > 0:
            obj.can_delete = False
        else:
            obj.can_delete = True
    form = BuildingTemplateForm()
    form.tag_types.choices = get_choices(TagType)
    if form.validate_on_submit():
        BuildingTemplate(name=str(form.name.data),
                         description=str(form.description.data),
                         tag_types=form.tag_types.data).save()
        return redirect(url_for('central.buildingtemplate'))
    return render_template('central/buildingtemplate.html', objs=objs, form=form)


@central.route('/buildingtemplate_delete', methods=['POST'])
@login_required
def buildingtemplate_delete():
    BuildingTemplate.objects(name=request.form.get('name')).delete()
    return redirect(url_for('central.buildingtemplate'))


@central.route('/building', methods=['GET', 'POST'])
@login_required
def building():
    page = request.args.get('page', 1, type=int)
    skip_size = (page-1)*PAGE_SIZE
    objs = Building.objects().skip(skip_size).limit(PAGE_SIZE)
    for obj in objs:
        if len(obj.tags) == 0:
            obj.can_delete = True
        else:
            obj.can_delete = False
    form = BuildingForm()
    form.template.choices = get_choices(BuildingTemplate)
    if form.validate_on_submit():
        Building(name=str(form.name.data),
                 description=str(form.description.data),
                 template=str(form.template.data)).save()
        return redirect(url_for('central.building'))
    return render_template('central/building.html', objs=objs, form=form)


@central.route('/building_delete', methods=['POST'])
@login_required
def building_delete():
    Building.objects(name=request.form.get('name')).delete()
    return redirect(url_for('central.building'))


@central.route('/building/<name>/metadata', methods=['GET', 'POST'])
@login_required
def building_metadata(name):
    if request.method == 'GET':
        metadata = Building._get_collection().find({'name': name}, {'metadata': 1, '_id': 0})[0]['metadata']
        metadata = [{'name': key, 'value': val} for key, val in metadata.iteritems()]
        return jsonify({'data': metadata})
    else:
        metadata = {pair['name']: pair['value'] for pair in request.get_json()['data']}
        Building.objects(name=name).update(set__metadata=metadata)
        return jsonify({'success': 'True'})


@central.route('/building/<building_name>/tags', methods=['GET'])
@login_required
def building_tags(building_name):
    return render_template('central/buildingtags.html', building_name=building_name)


@central.route('/building/<building_name>/tags_delete', methods=['POST'])
@login_required
def building_tags_delete(building_name):
    tag_name = request.form.get('tag_name')
    tag_value = request.form.get('tag_value')
    Building._get_collection().update(
        {'name': building_name},
        {'$pull': {'tags': {'name': tag_name, 'value': tag_value}}}
    )
    return redirect(url_for('central.building_tags', building_name=building_name))


@central.route('/building/<building_name>/tags/<tag_name>/<tag_value>/metadata', methods=['GET', 'POST'])
@login_required
def building_tags_metadata(building_name, tag_name, tag_value):
    if request.method == 'GET':
        metadata = Building._get_collection().aggregate([
            {'$unwind': '$tags'},
            {'$match': {'name': building_name, 'tags.name': tag_name, 'tags.value': tag_value}},
            {'$project': {'_id': 0, 'tags.metadata': 1}}
        ])['result'][0]['tags']['metadata']
        metadata = [{'name': key, 'value': val} for key, val in metadata.iteritems()]
        return jsonify({'data': metadata})
    else:
        metadata = {pair['name']: pair['value'] for pair in request.get_json()['data']}
        collection = Building._get_collection()
        tag = collection.aggregate([
            {'$unwind': '$tags'},
            {'$match': {'name': building_name, 'tags.name': tag_name, 'tags.value': tag_value}},
            {'$project': {'_id': 0, 'tags': 1}}
        ])['result'][0]['tags']
        tag['metadata'] = metadata
        collection.update(
            {'name': building_name},
            {'$pull': {'tags': {'name': tag_name, 'value': tag_value}}}
        )
        collection.update(
            {'name': building_name},
            {'$addToSet': {'tags': tag}}
        )
        return jsonify({'success': 'True'})


# ajax for adding a new tag for a building
@central.route('/building/<building_name>/add_tag', methods=['GET', 'POST'])
@login_required
def building_tags_ajax(building_name):
    if request.method == 'GET':
        template = Building.objects(name=building_name).first().template
        names = BuildingTemplate.objects(name=template).first().tag_types
        pairs = {name: TagType.objects(name=name).first().parents for name in names}
        tags = Building._get_collection().find(
            {'name': building_name},
            {'_id': 0, 'tags.name': 1, 'tags.value': 1, 'tags.parents': 1, 'tags.ancestors': 1}
        )[0]['tags']
        parents = set([pair['name']+pair['value'] for tag in tags for pair in tag['parents']])
        for tag in tags:
            tag['can_delete'] = tag['name']+tag['value'] not in parents
            tag['ancestors'] = [ancestor['name']+ancestor['value'] for ancestor in tag['ancestors']]
        return jsonify({'pairs': pairs, 'tags': tags, 'graph': get_tag_descendant_pairs()})
    else:
        data = request.get_json()['data']
        collection = Building._get_collection()
        ancestors = []
        if 'parents' in data:
            data['parents'] = [{'name': parent['name'], 'value': parent['value']} for parent in data['parents']]
            for parent in data['parents']:
                ancestors.extend(
                    collection.aggregate([
                        {'$unwind': '$tags'},
                        {'$match': {'name': building_name, 'tags.name': parent['name'], 'tags.value': parent['value']}},
                        {'$project': {'_id': 0, 'tags.ancestors': 1}}
                    ])['result'][0]['tags']['ancestors']
                )
            ancestors.extend(data['parents'])

        tag = {
            'name': data['name'],
            'value': data['value'],
            'metadata': {},
            'parents': [],
            'ancestors': ancestors
        }

        if 'parents' in data:
            tag['parents'] = data['parents']

        collection.update(
            {'name': building_name},
            {'$addToSet': {'tags': tag}}
        )
        return jsonify({'success': 'True'})



@central.route('/user', methods=['GET'])
@login_required
def user():
    return render_template('central/user.html')


@central.route('/user/add_user', methods=['GET', 'POST'])
@login_required
def user_ajax():
    if request.method == 'GET':
        objs = User.objects
        supers, locals, defaults = [], [], []
        for obj in objs:
            if obj.is_super():
                supers.append({'email': obj.email, 'name': obj.name})
            elif obj.is_local():

BuildingDepot/app/templates/central/building.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - Building{% endblock %}

{% block page_content %}
<div class="row">
    <div class="page-header">
        <h2>Building <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Add a New Building</a></h2>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add a New Building</h4>
                </div>
                <div class="modal-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>

    <div ng-app="myApp" ng-controller="metadataController">
    <div class="modal fade" id="metadata">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Metadata of Building {[ root.buildingName ]}</h4>
                </div>
                <div class="modal-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="pair in metadata">
                                <td><input ng-model="metadata[$index].name" type="text" class="form-control" value="{[ pair.name ]}"></td>
                                <td><input ng-model="metadata[$index].value" type="text" class="form-control" value="{[ pair.value ]}"></td>
                                <td><button class="close" ng-click="root.removeName($index)">&times;</button></td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="btn-group">
                        <button ng-click="root.addNewPair()" type="button" class="btn btn-info">Add a new pair</button>
                        <button ng-click="root.update()" type="button" class="btn btn-warning">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Template</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objs %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.template }}</td>
                    <td class="col-sm-4">{{ obj.description }}</td>
                    <td>
                        <a ng-click="root.select('{{ obj.name }}')" href="#metadata" data-toggle="modal" class="btn btn-info">Metadata</a>
                    </td>
                    <td>
                        <form action="{{ url_for('central.building_tags', building_name=obj.name) }}">
                        <input type="submit" value="Tags" class="btn btn-success">
                        </form>
                    </td>
                    {% if obj.can_delete %}
                    <td>
                        <form action="{{ url_for('central.building_delete') }}" method="POST">
                        <input type="hidden" value="{{ obj.name }}" name="name">
                        <input type="submit" value="Delete" class="btn btn-danger">
                        </form>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
     {{ super() }}
     <script>
        var app = angular.module("myApp", []);
        app.config(['$interpolateProvider', function($interpolateProvider) {
            $interpolateProvider.startSymbol('{[');
            $interpolateProvider.endSymbol(']}');
        }]);
        app.controller("metadataController", function($scope, $http) {
            $scope.root = {};
            $scope.root.addNewPair = function() {
                $scope.metadata.push({'name': '', 'value': ''});
            };
            $scope.root.removeName = function(index) {
                $scope.metadata.splice(index, 1);
            };
            $scope.root.select = function(buildingName) {
                this.buildingName = buildingName;
                var res = $http.get('/central/building/'+ buildingName + '/metadata');
                res.success(function(data) {
                    console.log(data);
                    $scope.metadata = data.data;
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
            $scope.root.update = function() {
                var res = $http.post('/central/building/'+ this.buildingName + '/metadata', {'data': $scope.metadata});
                res.success(function(data) {
                    confirm('Success');
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
        });
    </script>
{% endblock %}

BuildingDepot/app/templates/central/buildingtags.html
{% extends "index.html" %}

{% block title %}BuildingDepot - Building Tags{% endblock %}

{% block page_content %}
<div class="row" ng-app="myApp" ng-controller="metadataController">
    <div class="page-header">
        <h2>Tags of Building {{ building_name }} <a ng-init="root.addNewTag()" href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Add a New Building Tag</a></h2>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add a New Building Tag</h4>
                </div>
                <div class="modal-body">

                    <form class="form-horizontal" ng-submit="root.submit()">
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Name</label>
                            <div class="col-lg-10">
                                <select required class="form-control" ng-model="selectedName" ng-options="name for name in names"></select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label">Value</label>
                            <div class="col-lg-10">
                                <input ng-model="value" required class="form-control" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label">Parents</label>
                            <div class="col-lg-10">
                                <select multiple class="form-control" ng-model="selectedParents" ng-options="tag.value group by tag.name for tag in tags | optionFilter:this "></select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-12">
                                <button class="btn btn-success pull-right" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div>
    <div class="modal fade" id="metadata">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Metadata of Building {[ root.buildingName ]} Tag {[ root.tagName ]} {[ root.tagValue ]} </h4>
                </div>
                <div class="modal-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="pair in metadata">
                                <td><input ng-model="metadata[$index].name" type="text" class="form-control" value="{[ pair.name ]}"></td>
                                <td><input ng-model="metadata[$index].value" type="text" class="form-control" value="{[ pair.value ]}"></td>
                                <td><button class="close" ng-click="root.removeName($index)">&times;</button></td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="btn-group">
                        <button ng-click="root.addNewPair()" type="button" class="btn btn-info">Add a new pair</button>
                        <button ng-click="root.update()" type="button" class="btn btn-warning">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-2">
        <form class="form-vertical">
            <div class="form-group">
            <label class="col-lg-2 control-label">Tag</label>
            <select class="form-control" ng-model="selectedTag" ng-options="tag.name+' '+tag.value group by tag.name for tag in tags">
                <option value="">-- choose tag --</option>
            </select>
            </div>

            <div class="form-group">
            <label class="col-lg-2 control-label">SubTag</label>
            <select class="form-control" ng-model="selectedSubTag" ng-options="name for name in names | subTagFilter:this">
                <option value="">-- choose subtag --</option>
            </select>
            </div>
        </form>
    </div>


    <div class="col-sm-10">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Parents</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="tag in tags | contentFilter:this | orderBy:['name', 'value']">
                    <td>{[ tag.name ]}</td>
                    <td>{[ tag.value ]}</td>
                    <td>
                        <p ng-repeat="parent in tag.parents">
                            {[ parent.name ]} {[ parent.value ]}
                        </p>
                    </td>
                    <td>
                        <a ng-click="root.select('{{ building_name }}', tag.name, tag.value)" href="#metadata" data-toggle="modal" class="btn btn-info">Metadata</a>
                    </td>
                    <td ng-show="tag.can_delete">
                        <form action="{{ url_for('central.building_tags_delete', building_name=building_name) }}" method="POST">
                        <input type="hidden" value="{[ tag.name ]}" name="tag_name">
                        <input type="hidden" value="{[ tag.value ]}" name="tag_value">
                        <input type="submit" value="Delete" class="btn btn-danger">
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
     {{ super() }}
     <script>
        var app = angular.module("myApp", []);
        app.config(['$interpolateProvider', function($interpolateProvider) {
            $interpolateProvider.startSymbol('{[');
            $interpolateProvider.endSymbol(']}');
        }]);
        app.controller("metadataController", function($scope, $http) {
            $scope.root = {};
            $scope.root.addNewPair = function() {
                $scope.metadata.push({'name': '', 'value': ''});
            };
            $scope.root.removeName = function(index) {
                $scope.metadata.splice(index, 1);
            };
            $scope.root.select = function(buildingName, tagName, tagValue) {
                this.buildingName = buildingName;
                this.tagName = tagName;
                this.tagValue = tagValue;
                var res = $http.get('/central/building/'+ buildingName + '/tags/' + tagName + '/' + tagValue + '/metadata');
                res.success(function(data) {
                    console.log(data);
                    $scope.metadata = data.data;
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
            $scope.root.update = function() {
                var res = $http.post('/central/building/'+ this.buildingName + '/tags/' + this.tagName + '/' + this.tagValue + '/metadata', {'data': $scope.metadata});
                res.success(function(data) {
                    confirm('Success');
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
            $scope.root.addNewTag = function() {
                var res = $http.get('/central/building/'+ '{{ building_name }}' + '/add_tag');
                res.success(function(data) {
                    $scope.pairs = data.pairs;
                    $scope.graph = data.graph;
                    $scope.tags = data.tags;
                    $scope.names = Object.keys($scope.pairs);
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
            $scope.root.submit = function() {
                var data = {
                    'name': $scope.selectedName,
                    'value': $scope.value,
                    'parents': $scope.selectedParents
                }
                for (var i = 0; i < $scope.tags.length; i++) {
                    if ($scope.tags[i].name === $scope.selectedName && $scope.tags[i].value === $scope.value) {
                        alert("There is already a tag with the same name and value");
                        return;
                    }
                }
                var res = $http.post('/central/building/'+ '{{ building_name }}' + '/add_tag', {'data': data});
                res.success(function(data) {
                    confirm('Success');
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
        });

        app.filter('optionFilter', [function() {
            return function(input, scope) {
                var parents = scope.pairs[scope.selectedName];
                return input.filter(function(elem) {
                    return parents.indexOf(elem.name) > -1;
                });
            };
        }]);

        app.filter('subTagFilter', [function() {
            return function(input, scope) {
                var selectedTag = scope.selectedTag;
                if (selectedTag !== null && selectedTag !== undefined) {
                    input = scope.graph[selectedTag.name];
                    return input.filter(function(elem) {
                        return scope.names.indexOf(elem) > -1;
                    });
                }
                return input;
            };
        }]);

        function isInvalid(obj) {
            return obj === null || obj === undefined;
        }
        app.filter('contentFilter', [function() {
            return function(input, scope) {
                var selectedTag = scope.selectedTag;
                var selectedSubTag = scope.selectedSubTag;
                if (isInvalid(selectedTag)) {
                    if (isInvalid(selectedSubTag)) {
                        return input;
                    }
                    return input.filter(function(elem) {
                        return elem.name === selectedSubTag;
                    });
                } else {
                    if (isInvalid(selectedSubTag)) {
                        return [selectedTag];
                    }
                    var ancestor = selectedTag.name+selectedTag.value;
                    return input.filter(function(elem) {
                        return elem.name ===  selectedSubTag && elem.ancestors.indexOf(ancestor) > -1;
                    });
                }
            };
        }]);
    </script>
{% endblock %}

BuildingDepot/app/templates/central/buildingtemplate.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - BuildingTemplate{% endblock %}

{% block page_content %}
<div class="row">
    <div class="page-header">
        <h2>BuildingTemplate <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Add a New BuildingTemplate</a></h2>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add a New BuildingTemplate</h4>
                </div>
                <div class="modal-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>TagTypes</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objs %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td class="col-sm-4">{{ obj.description }}</td>
                    <td>
                        <select multiple disabled class="form-control">
                            {% for tag_type in obj.tag_types %}
                            <option>{{ tag_type }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    {% if obj.can_delete %}
                    <td>
                        <form action="{{ url_for('central.buildingtemplate_delete') }}" method="POST">
                        <input type="hidden" value="{{ obj.name }}" name="name">
                        <input type="submit" value="Delete" class="btn btn-danger">
                        </form>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock %}