DataService/app/service/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SelectMultipleField, SubmitField, SelectField, BooleanField
from wtforms.validators import DataRequired


class SensorForm(Form):
    source_name = StringField('Source Name')
    source_identifier = StringField('Source Identifier')
    building = SelectField('Building', validators=[DataRequired()])
    submit = SubmitField('Submit')


class SensorGroupForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    building = SelectField('Building', validators=[DataRequired()])
    submit = SubmitField('Submit')


class UserGroupForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description')
    submit = SubmitField('Submit')


class PermissionForm(Form):
    user_group = SelectField('User Group', validators=[DataRequired()])
    sensor_group = SelectField('Sensor Group', validators=[DataRequired()])
    permission = SelectField('Building', choices=[('r', 'r'), ('r/w', 'r/w')], validators=[DataRequired()])
    submit = SubmitField('Submit')


class PermissionQueryForm(Form):
    user = StringField('User Email', validators=[DataRequired()])
    sensor = StringField('Sensor ID', validators=[DataRequired()])
    submit = SubmitField('Submit')

DataService/app/service/__init__.py
from flask import Blueprint

service = Blueprint('service', __name__)

from . import views

DataService/app/service/views.py
from flask import render_template, request, redirect, url_for, jsonify, flash
from . import service
from ..models.ds_models import *
from .forms import *
from .utils import *
from uuid import uuid4

from .. import r, influx


@service.route('/sensor', methods=['GET', 'POST'])
def sensor():
    page = request.args.get('page', 1, type=int)
    skip_size = (page-1)*PAGE_SIZE
    objs = Sensor.objects().skip(skip_size).limit(PAGE_SIZE)
    for obj in objs:
        obj.can_delete = True

    form = SensorForm()
    form.building.choices = get_building_choices(current_app.config['NAME'])
    if form.validate_on_submit():
        Sensor(name=str(uuid4()),
               source_name=str(form.source_name.data),
               source_identifier=str(form.source_identifier.data),
               building=str(form.building.data)).save()
        return redirect(url_for('service.sensor'))
    return render_template('service/sensor.html', objs=objs, form=form)


@service.route('/sensor/<name>/metadata', methods=['GET', 'POST'])
def sensor_metadata(name):
    if request.method == 'GET':
        metadata = Sensor._get_collection().find({'name': name}, {'metadata': 1, '_id': 0})[0]['metadata']
        metadata = [{'name': key, 'value': val} for key, val in metadata.iteritems()]
        return jsonify({'data': metadata})
    else:
        metadata = {pair['name']: pair['value'] for pair in request.get_json()['data'] if pair['name'] != ''}
        building = Sensor.objects(name=name).first()
        building.update(set__metadata=metadata)
        return jsonify({'success': 'True'})


@service.route('/sensor/<name>/subscribers', methods=['GET', 'POST'])
def sensor_subscribers(name):
    if request.method == 'GET':
        subscribers = r.smembers('subscribers:{}'.format(name))
        data = [{'email': subscriber} for subscriber in subscribers]
        return jsonify({'subscribers': data})
    else:
        new_subscribers = [subscriber['email'] for subscriber in request.get_json()['data']]
        if validate_users(new_subscribers):
            old_subscribers = r.smembers('subscribers:{}'.format(name))
            added, deleted = get_add_delete(old_subscribers, new_subscribers)
            pipe = r.pipeline()
            for email in added:
                pipe.sadd('subscribed_sensors:{}'.format(email), name)
            for email in deleted:
                pipe.srem('subscribed_sensors:{}'.format(email), name)

            pipe.delete('subscribers:{}'.format(name))
            for subscriber in new_subscribers:
                pipe.sadd('subscribers:{}'.format(name), subscriber)
            pipe.execute()
            return jsonify({'success': 'True'})
        return jsonify({'success': 'False'})


@service.route('/sensor/<name>/timeseries', methods=['POST'])
def sensor_timeseries(name):
    points = [[int(pair['time']), pair['value']] for pair in request.get_json()['data']]
    data = [{
        'name': name,
        'columns': ['time', 'value'],
        'points': points
    }]

    max_point = max(points)
    emails = r.smembers('subscribers:{}'.format(name))
    pipe = r.pipeline()
    for email in emails:
        pipe.set('latest_point:{}:{}'.format(name, email), '{}-{}'.format(max_point[0], max_point[1]))
    pipe.execute()

    influx.write_points(data)
    return jsonify({'success': 'True'})


@service.route('/sensor_delete', methods=['POST'])
def sensor_delete():
    #cache process
    sensor = Sensor.objects(name=request.form.get('name')).first()
    tags = ['tag:{}:{}:{}'.format(sensor.building, tag.name, tag.value) for tag in sensor.tags]
    pipe = r.pipeline()
    for tag in tags:
        pipe.srem(tag, sensor.name)

    deleted = [tag.replace('tag', 'tag-sensorgroup', 1) for tag in tags]
    for key in deleted:
        for name in r.smembers(key):
            pipe.srem('sensorgroup:{}'.format(name), sensor.name)

    # clean subscribers
    emails = r.smembers('subscribers:{}'.format(sensor.name))
    pipe.delete('subscribers:{}'.format(sensor.name))
    for email in emails:
        pipe.srem('subscribed_sensors:{}'.format(email), sensor.name)

    pipe.delete('sensor:{}'.format(sensor.name))
    pipe.execute()
    #cache process done

    Sensor.objects(name=sensor.name).delete()
    return redirect(url_for('service.sensor'))


@service.route('/sensor/<name>/tags', methods=['GET', 'POST'])
def sensor_tags(name):
    if request.method == 'GET':
        obj = Sensor.objects(name=name).first()
        tags_owned = [{'name': tag.name, 'value': tag.value} for tag in obj.tags]
        tags = get_building_tags(obj.building)
        return jsonify({'tags': tags, 'tags_owned': tags_owned})
    else:
        tags = request.get_json()['data']

        # cache process
        sensor = Sensor.objects(name=name).first()
        building = sensor.building
        old = ['tag:{}:{}:{}'.format(building, tag.name, tag.value) for tag in sensor.tags]
        new = ['tag:{}:{}:{}'.format(building, tag['name'], tag['value']) for tag in tags]
        added, deleted = get_add_delete(old, new)
        pipe = r.pipeline()
        for tag in added:
            pipe.sadd(tag, name)
        for tag in deleted:
            pipe.srem(tag, name)
        pipe.execute()
        # cache process done
        Sensor.objects(name=name).update(set__tags=tags)

        added = [tag.replace('tag', 'tag-sensorgroup', 1) for tag in added]
        deleted = [tag.replace('tag', 'tag-sensorgroup', 1) for tag in deleted]

        pipe = r.pipeline()
        for key in added:
            for sensorgroup_name in r.smembers(key):
                sensorgroup = SensorGroup.objects(name=sensorgroup_name).first()
                sensorgroup_tags = {'tag:{}:{}:{}'.format(building, tag.name, tag.value) for tag in sensorgroup.tags}
                if sensorgroup_tags.issubset(new):
                    pipe.sadd('sensorgroup:{}'.format(sensorgroup_name), sensor.name)
                    pipe.sadd('sensor:{}'.format(sensor.name), sensorgroup_name)

        for key in deleted:
            for sensorgroup_name in r.smembers(key):
                pipe.srem('sensorgroup:{}'.format(sensorgroup_name), sensor.name)
                pipe.srem('sensor:{}'.format(sensor.name), sensorgroup_name)

        pipe.execute()

        return jsonify({'success': 'True'})


@service.route('/sensorgroup', methods=['GET', 'POST'])
def sensorgroup():
    page = request.args.get('page', 1, type=int)
    skip_size = (page-1)*PAGE_SIZE
    objs = SensorGroup.objects().skip(skip_size).limit(PAGE_SIZE)
    for obj in objs:
        obj.can_delete = True

    form = SensorGroupForm()
    form.building.choices = get_building_choices(current_app.config['NAME'])
    if form.validate_on_submit():
        SensorGroup(name=str(form.name.data),
                    description=str(form.description.data),
                    building=str(form.building.data)).save()
        return redirect(url_for('service.sensorgroup'))
    return render_template('service/sensorgroup.html', objs=objs, form=form)


@service.route('/sensorgroup/<name>/tags', methods=['GET', 'POST'])
def sensorgroup_tags(name):
    if request.method == 'GET':
        obj = SensorGroup.objects(name=name).first()
        tags_owned = [{'name': tag.name, 'value': tag.value} for tag in obj.tags]
        tags = get_building_tags(obj.building)
        return jsonify({'tags': tags, 'tags_owned': tags_owned})
    else:
        tags = request.get_json()['data']
        #cache process
        sensorgroup = SensorGroup.objects(name=name).first()
        old = ['tag-sensorgroup:{}:{}:{}'.format(sensorgroup.building, tag.name, tag.value) for tag in sensorgroup.tags]
        new = ['tag-sensorgroup:{}:{}:{}'.format(sensorgroup.building, tag['name'], tag['value']) for tag in tags]
        added, deleted = get_add_delete(old, new)
        pipe = r.pipeline()
        for tag in added:
            pipe.sadd(tag, name)
        for tag in deleted:
            pipe.srem(tag, name)

        # recalculate the sensors that this sensorgroup contains
        tags_owned = ['tag:{}:{}:{}'.format(sensorgroup.building, tag['name'], tag['value']) for tag in tags]

        old_sensors = r.smembers('sensorgroup:{}'.format(name))
        new_sensors = r.sinter(tags_owned) if len(tags_owned) > 0 else []
        added, deleted = get_add_delete(old_sensors, new_sensors)

        for sensor_name in added:
            pipe.sadd('sensor:{}'.format(sensor_name), name)
        for sensor_name in deleted:
            pipe.srem('sensor:{}'.format(sensor_name), name)

        r.delete('sensorgroup:{}'.format(name))
        for item in new_sensors:
            pipe.sadd('sensorgroup:{}'.format(name), item)
        pipe.execute()
        #cache process done
        SensorGroup.objects(name=name).update(set__tags=tags)
        return jsonify({'success': 'True'})


@service.route('/sensorgroup_delete', methods=['POST'])
def sensorgroup_delete():
    # cache process
    sensorgroup = SensorGroup.objects(name=request.form.get('name')).first()
    pipe = r.pipeline()

    for sensor_name in r.smembers('sensorgroup:{}'.format(sensorgroup.name)):
        pipe.srem('sensor:{}'.format(sensor_name), sensorgroup.name)

    pipe.delete('sensorgroup:{}'.format(sensorgroup.name))
    for tag in sensorgroup.tags:
        pipe.srem('tag-sensorgroup:{}:{}:{}'.format(sensorgroup.building, tag.name, tag.value), sensorgroup.name)
    pipe.execute()
    # cache process done

    SensorGroup.objects(name=sensorgroup.name).delete()
    return redirect(url_for('service.sensorgroup'))


@service.route('/usergroup', methods=['GET', 'POST'])
def usergroup():
    page = request.args.get('page', 1, type=int)
    skip_size = (page-1)*PAGE_SIZE
    objs = UserGroup.objects().skip(skip_size).limit(PAGE_SIZE)
    for obj in objs:
        obj.can_delete = True

    form = UserGroupForm()
    if form.validate_on_submit():
        UserGroup(name=str(form.name.data),

DataService/app/templates/service/permission.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - Permission{% endblock %}

{% block page_content %}
<div class="row">
    <div class="page-header">
        <h2>Permission <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Add a New Permission Pair</a></h2>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add a New Permission Pair</h4>
                </div>
                <div class="modal-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>

    <div>
        <div class="col-sm-12">
            <table class="table">
                <thead
                    <tr>
                        <th>User Group</th>
                        <th>Sensor Group</th>
                        <th>Permission</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in objs %}
                    <tr>
                        <td>{{ obj.user_group }}</td>
                        <td>{{ obj.sensor_group }}</td>
                        <td>{{ obj.permission }}</td>
                        {% if obj.can_delete %}
                        <td>
                            <form action="{{ url_for('service.permission_delete') }}" method="POST">
                            <input type="hidden" value="{{ obj.user_group + ':-:' + obj.sensor_group }}" name="name">
                            <input type="submit" value="Delete" class="btn btn-danger">
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

DataService/app/templates/service/query.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - Permission Query{% endblock %}

{% block page_content %}
<div class="row">
    <div class="page-header">
        <h2>Permission Query</h2>
        <div class="col-sm-4">
        {{ wtf.quick_form(form) }}
        {% if res %}
            <h3>Permission: {{ res }}</h3>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

DataService/app/templates/service/sensorgroup.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - Sensor Group{% endblock %}

{% block page_content %}
<div class="row">
    <div class="page-header">
        <h2>Sensor Group <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Add a New Sensor Group</a></h2>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add a New Sensor Group</h4>
                </div>
                <div class="modal-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>



    <div ng-app="myApp" ng-controller="metadataController">
        <div class="modal fade" id="tags">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Assigned Tags for Sensor Group {[ sensorGroupName ]} </h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <table class="table" ng-show="tags_owned.length > 0">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="tag in tags_owned">
                                        <td><input disabled ng-model="tags_owned[$index].name" type="text" class="form-control" value="{[ tag.name ]}"></td>
                                        <td><input disabled ng-model="tags_owned[$index].value" type="text" class="form-control" value="{[ tag.value ]}"></td>
                                        <td><button class="close" ng-click="root.removeExistingTag($index)">&times;</button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="tag in addedTags">
                                        <td><select ng-model="addedTags[$index].name" class="form-control" ng-options="name for name in names | orderBy: name"></select></td>
                                        <td><select ng-model="addedTags[$index].value" class="form-control" ng-options="value for value in values | valueFilter: this: addedTags[$index].name | orderBy: value"></select></td>
                                        <td><button class="close" ng-click="root.removeTag($index)">&times;</button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>


                        <div class="btn-group">
                            <button ng-click="root.addNewTag()" type="button" class="btn btn-info">Add a new tag</button>
                            <button ng-click="root.updateTags()" type="button" class="btn btn-warning">Update</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Building</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in objs %}
                    <tr>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.description }}</td>
                        <td>{{ obj.building }}</td>
                        <td>
                            <a ng-click="root.tags('{{ obj.name }}')" href="#tags" data-toggle="modal" class="btn btn-info">Tags</a>
                        </td>
                        {% if obj.can_delete %}
                        <td>
                            <form action="{{ url_for('service.sensorgroup_delete') }}" method="POST">
                            <input type="hidden" value="{{ obj.name }}" name="name">
                            <input type="submit" value="Delete" class="btn btn-danger">
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
     {{ super() }}
     <script>
        var app = angular.module("myApp", []);
        app.config(['$interpolateProvider', function($interpolateProvider) {
            $interpolateProvider.startSymbol('{[');
            $interpolateProvider.endSymbol(']}');
        }]);
        app.controller("metadataController", function($scope, $http) {
            $scope.root = {};
            $scope.root.tags = function(sensorGroupName) {
                $scope.addedTags = [];
                $scope.sensorGroupName = sensorGroupName;
                var res = $http.get('/service/sensorgroup/' + sensorGroupName + '/tags');
                res.success(function(data) {
                    $scope.tags = data.tags;
                    $scope.tags_owned = data.tags_owned;
                    $scope.names = Object.keys($scope.tags);
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
            $scope.root.addNewTag = function() {
                $scope.addedTags.push({'name': '', 'value': ''});
            };
            $scope.root.removeExistingTag = function(index) {
                $scope.tags_owned.splice(index, 1);
            };
            $scope.root.removeTag = function(index) {
                $scope.addedTags.splice(index, 1);
            };
            $scope.root.updateTags = function() {
                tags = $scope.tags_owned.concat($scope.addedTags);
                if (tags.length > 0) {
                    var set = {};
                    for (var i = 0; i < tags.length; i++) {
                        if (tags[i].name === '' || tags[i].value === '') {
                            alert('There is a name or value that is not specified');
                            return;
                        }
                        if (set[tags[i].name+tags[i].value]) {
                            alert('There is a tag that is specified more than once');
                            return;
                        }
                        set[tags[i].name+tags[i].value] = true;
                    }
                }

                var res = $http.post('/service/sensorgroup/'+ $scope.sensorGroupName + '/tags', {'data': tags});
                res.success(function(data) {
                    confirm('Success');
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
        });
        app.filter('valueFilter', [function() {
            return function(input, scope, name) {
                return scope.tags[name];
            };
        }]);
    </script>
{% endblock %}

DataService/app/templates/service/usergroup.html
{% extends "index.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BuildingDepot - User Group{% endblock %}

{% block page_content %}
<div class="row">
    <div class="page-header">
        <h2>User Group <a href="#myModal" data-toggle="modal" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-hand-up"></span> Add a New User Group</a></h2>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add a New User Group</h4>
                </div>
                <div class="modal-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>



    <div ng-app="myApp" ng-controller="metadataController">
        <div class="modal fade" id="users">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Assigned Users for User Group {[ userGroupName ]} </h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>User Email</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="email in emails">
                                        <td><input disabled ng-model="emails[$index]" type="text" class="form-control" value="{[ email ]}"></td>
                                        <td><button class="close" ng-click="root.removeExistingUser($index)">&times;</button></td>
                                    </tr>
                                    <tr ng-repeat="user in addedUsers">
                                        <td><input ng-model="addedUsers[$index].email" type="text" class="form-control" value="{[ user.email ]}"></td>
                                        <td><button class="close" ng-click="root.removeUser($index)">&times;</button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="btn-group">
                            <button ng-click="root.addNewUser()" type="button" class="btn btn-info">Add a new user</button>
                            <button ng-click="root.updateUsers()" type="button" class="btn btn-warning">Update</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in objs %}
                    <tr>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.description }}</td>
                        <td>
                            <a ng-click="root.users('{{ obj.name }}')" href="#users" data-toggle="modal" class="btn btn-info">Users</a>
                        </td>
                        {% if obj.can_delete %}
                        <td>
                            <form action="{{ url_for('service.usergroup_delete') }}" method="POST">
                            <input type="hidden" value="{{ obj.name }}" name="name">
                            <input type="submit" value="Delete" class="btn btn-danger">
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
     {{ super() }}
     <script>
        var app = angular.module("myApp", []);
        app.config(['$interpolateProvider', function($interpolateProvider) {
            $interpolateProvider.startSymbol('{[');
            $interpolateProvider.endSymbol(']}');
        }]);
        app.controller("metadataController", function($scope, $http) {
            $scope.root = {};
            $scope.root.users = function(userGroupName) {
                $scope.addedUsers = [];
                $scope.userGroupName = userGroupName;
                var res = $http.get('/service/usergroup/' + userGroupName + '/users');
                res.success(function(data) {
                    $scope.emails = data.users;
                });
                res.error(function() {
                    alert("Ajax failed");
                });
            };
            $scope.root.addNewUser = function() {
                $scope.addedUsers.push({'email': ''});
            };
            $scope.root.removeExistingUser = function(index) {
                $scope.emails.splice(index, 1);
            };
            $scope.root.removeUser = function(index) {
                $scope.addedUsers.splice(index, 1);
            };
            $scope.root.updateUsers = function() {
                var addedUsers = [];
                for (var i = 0; i < $scope.addedUsers.length; i++) {
                    addedUsers.push($scope.addedUsers[i].email);
                }
                users = $scope.emails.concat(addedUsers);
                if (users.length > 0) {
                    var set = {};
                    for (var i = 0; i < users.length; i++) {
                        if (users[i] === '') {
                            alert('There is an email that is not specified');
                            return;
                        }
                        if (set[users[i]]) {
                            alert('There is a tag that is specified more than once');
                            return;
                        }
                        set[users[i]] = true;
                    }
                }

                var res = $http.post('/service/usergroup/'+ $scope.userGroupName + '/users', {'data': users});
                res.success(function(data) {
                    var success = data.success;
                    if (success === 'True') {
                        confirm('Success');
                    } else {
                        alert("There is one or more emails that are not in the database");
                    }

                });
                res.error(function() {
                    alert("Ajax Failure");
                });
            };
        });
    </script>
{% endblock %}